/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#include <pocketsphinx.h>

typedef int bool;
#define false 0
#define true 1

typedef fsg_set_t FsgSet;
typedef ps_decoder_t Decoder;
typedef ps_lattice_t Lattice;


#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1 
#define  SWIG_IOError        	   -2 
#define  SWIG_RuntimeError   	   -3 
#define  SWIG_IndexError     	   -4 
#define  SWIG_TypeError      	   -5 
#define  SWIG_DivisionByZero 	   -6 
#define  SWIG_OverflowError  	   -7 
#define  SWIG_SyntaxError    	   -8 
#define  SWIG_ValueError     	   -9 
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12 
#define  SWIG_NullReferenceError   -13




SWIGINTERN void SWIG_JavaException(JNIEnv *jenv, int code, const char *msg) {
  SWIG_JavaExceptionCodes exception_code = SWIG_JavaUnknownError;
  switch(code) {
  case SWIG_MemoryError:
    exception_code = SWIG_JavaOutOfMemoryError;
    break;
  case SWIG_IOError:
    exception_code = SWIG_JavaIOException;
    break;
  case SWIG_SystemError:
  case SWIG_RuntimeError:
    exception_code = SWIG_JavaRuntimeException;
    break;
  case SWIG_OverflowError:
  case SWIG_IndexError:
    exception_code = SWIG_JavaIndexOutOfBoundsException;
    break;
  case SWIG_DivisionByZero:
    exception_code = SWIG_JavaArithmeticException;
    break;
  case SWIG_SyntaxError:
  case SWIG_ValueError:
  case SWIG_TypeError:
    exception_code = SWIG_JavaIllegalArgumentException;
    break;
  case SWIG_UnknownError:
  default:
    exception_code = SWIG_JavaUnknownError;
    break;
  }
  SWIG_JavaThrowException(jenv, exception_code, msg);
}


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* signed char[] support */
static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetByteArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (signed char*) calloc(sz, sizeof(signed char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  (*jenv)->ReleaseByteArrayElements(jenv, input, jarr, 0);
}

static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = (*jenv)->NewByteArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetByteArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  (*jenv)->ReleaseByteArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned char*) calloc(sz, sizeof(unsigned char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* short[] support */
static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (short*) calloc(sz, sizeof(short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned short*) calloc(sz, sizeof(unsigned short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* int[] support */
static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (int*) calloc(sz, sizeof(int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned int*) calloc(sz, sizeof(unsigned int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* long[] support */
static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (long*) calloc(sz, sizeof(long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned long*) calloc(sz, sizeof(unsigned long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (jlong*) calloc(sz, sizeof(jlong)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* float[] support */
static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetFloatArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (float*) calloc(sz, sizeof(float)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, input, jarr, 0);
}

static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = (*jenv)->NewFloatArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetFloatArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* double[] support */
static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetDoubleArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (double*) calloc(sz, sizeof(double)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, input, jarr, 0);
}

static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = (*jenv)->NewDoubleArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetDoubleArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


#endif


typedef cmd_ln_t Config;
typedef jsgf_t Jsgf;
typedef jsgf_rule_t JsgfRule;
typedef feat_t Feature;
typedef fe_t FrontEnd;
typedef fsg_model_t FsgModel;
typedef logmath_t LogMath;
typedef ngram_model_t NGramModel;
typedef ngram_model_t NGramModelSet;



typedef struct {
    char *hypstr;
    char *uttid;
    int best_score;
} Hypothesis;

typedef struct {
    ps_seg_t *ptr;
    char *word;
    int32 ascr;
    int32 lscr;
    int32 lback;
    int start_frame;
    int end_frame;
} Segment;

typedef struct {
    ps_nbest_t *ptr;
} NBest;

SWIGINTERN Hypothesis *new_Hypothesis(char const *hypstr,char const *uttid,int best_score){
        Hypothesis *h = ckd_malloc(sizeof *h);
        if (hypstr)
            h->hypstr = ckd_salloc(hypstr);
        if (uttid)
            h->uttid = ckd_salloc(uttid);
        h->best_score = best_score;
        return h;  
  }
SWIGINTERN void delete_Hypothesis(Hypothesis *self){
        ckd_free(self->hypstr);
        ckd_free(self->uttid);
        ckd_free(self);
    }
SWIGINTERN Segment *new_Segment(ps_seg_t *ptr){
        if (!ptr)
            return NULL;

        Segment *seg = ckd_malloc(sizeof *seg);
        seg->ptr = ptr;
        seg->word = 0;

        return seg;
    }
SWIGINTERN void delete_Segment(Segment *self){
        ps_seg_free(self->ptr);
        ckd_free(self->word);
        ckd_free(self);
    }
SWIGINTERN NBest *new_NBest(ps_nbest_t *ptr){
        if (!ptr)
            return NULL;

        NBest *nbest = ckd_malloc(sizeof *nbest);
        nbest->ptr = ptr;

        return nbest;
    }
SWIGINTERN void delete_NBest(NBest *self){
          ps_nbest_free(self->ptr);
          ckd_free(self);
    }
SWIGINTERN Hypothesis *NBest_hyp(NBest *self){
        int32 score;
        const char *hyp = ps_nbest_hyp(self->ptr, &score);
        // TODO: refactor; what is this empty argument?
        return new_Hypothesis(hyp, "", score);
    }
SWIGINTERN Segment *NBest_seg(NBest *self){
        int32 score;
        // TODO: refactor; use 'score' value
        return new_Segment(ps_nbest_seg(self->ptr, &score));
    }
SWIGINTERN Decoder *new_Decoder__SWIG_0(){
        Decoder *d = ps_init(cmd_ln_init(NULL, ps_args(), FALSE, NULL));
        return d;
        return NULL;
    }
SWIGINTERN Decoder *new_Decoder__SWIG_1(Config *c){
        Decoder *d = ps_init(c);
        return d;
    }
SWIGINTERN void delete_Decoder(Decoder *self){
        ps_free(self);
    }
SWIGINTERN void Decoder_reinit(Decoder *self,Config *config,int *errcode){
        *errcode = ps_reinit(self, config);
    }
SWIGINTERN void Decoder_load_dict(Decoder *self,char const *fdict,char const *ffilter,char const *format,int *errcode){
        *errcode = ps_load_dict(self, fdict, ffilter, format);
    }
SWIGINTERN void Decoder_save_dict(Decoder *self,char const *dictfile,char const *format,int *errcode){
        *errcode = ps_save_dict(self, dictfile, format);
    }
SWIGINTERN void Decoder_add_word(Decoder *self,char const *word,char const *phones,int update,int *errcode){
        *errcode = ps_add_word(self, word, phones, update);
    }
SWIGINTERN Lattice *Decoder_get_lattice(Decoder *self){
        return ps_lattice_retain(ps_get_lattice(self));
    }
SWIGINTERN Config *Decoder_get_config(Decoder *self){
        return cmd_ln_retain(ps_get_config(self));
    }
SWIGINTERN Config *Decoder_default_config(){
        return cmd_ln_parse_r(NULL, ps_args(), 0, NULL, FALSE);
    }
SWIGINTERN void Decoder_start_utt(Decoder *self,char const *uttid,int *errcode){
        *errcode = ps_start_utt(self, uttid);
    }
SWIGINTERN char const *Decoder_get_uttid(Decoder *self){
        return ps_get_uttid(self);
    }
SWIGINTERN void Decoder_end_utt(Decoder *self,int *errcode){
        *errcode = ps_end_utt(self);
    }
SWIGINTERN int Decoder_process_raw(Decoder *self,void const *SDATA,size_t NSAMP,bool no_search,bool full_utt,int *errcode){
        NSAMP /= sizeof(int16);
        return *errcode = ps_process_raw(self, SDATA, NSAMP, no_search, full_utt);
    }
SWIGINTERN int Decoder_decode_raw(Decoder *self,FILE *f,int *errcode){
        *errcode = ps_decode_raw(self, f, 0, -1);
        return *errcode;
    }
SWIGINTERN Hypothesis *Decoder_hyp(Decoder *self){
        char const *hyp, *uttid;
        int32 best_score;
        hyp = ps_get_hyp(self, &best_score, &uttid);
        return hyp ? new_Hypothesis(hyp, uttid, best_score) : NULL;
    }
SWIGINTERN NBest *Decoder_nbest(Decoder *self){
        return new_NBest(ps_nbest(self, 0, -1, NULL, NULL));
    }
SWIGINTERN Segment *Decoder_seg(Decoder *self){
        int32 best_score;
        return new_Segment(ps_seg_iter(self, &best_score));
    }
SWIGINTERN FrontEnd *Decoder_get_fe(Decoder *self){
        return ps_get_fe(self);
    }
SWIGINTERN Feature *Decoder_get_feat(Decoder *self){
        return ps_get_feat(self);
    }
SWIGINTERN NGramModelSet *Decoder_get_lmset(Decoder *self){
        return ngram_model_retain(ps_get_lmset(self));
    }
SWIGINTERN NGramModelSet *Decoder_update_lmset(Decoder *self,NGramModelSet *lm_set){
        ngram_model_t *new_lm_set = ps_update_lmset(self, lm_set);
        return new_lm_set ? ngram_model_retain(new_lm_set) : NULL;
    }
SWIGINTERN FsgSet *Decoder_get_fsgset(Decoder *self){
        return ps_get_fsgset(self);
    }
SWIGINTERN FsgSet *Decoder_update_fsgset(Decoder *self){
        ps_update_fsgset(self);
    }
SWIGINTERN LogMath *Decoder_get_logmath(Decoder *self){
        return logmath_retain(ps_get_logmath(self));
    }
SWIGINTERN int Decoder_n_frames(Decoder *self){
        return ps_get_n_frames(self);
    }
SWIGINTERN Lattice *new_Lattice__SWIG_0(char const *path){
        return ps_lattice_read(NULL, path);
    }
SWIGINTERN Lattice *new_Lattice__SWIG_1(Decoder *decoder,char *path){
        return ps_lattice_read(decoder, path);
    }
SWIGINTERN void delete_Lattice(Lattice *self){
        ps_lattice_free(self);
    }
SWIGINTERN void Lattice_write(Lattice *self,char const *path,int *errcode){
        *errcode = ps_lattice_write(self, path);
    }
SWIGINTERN void Lattice_write_htk(Lattice *self,char const *path,int *errcode){
        *errcode = ps_lattice_write_htk(self, path);
    }
SWIGINTERN FsgSet *new_FsgSet(void *ptr){
	return ptr;
    }
SWIGINTERN void delete_FsgSet(FsgSet *self){
	return;
    }
SWIGINTERN FsgModel *FsgSet_add(FsgSet *self,char const *name,FsgModel *model){
        return fsg_set_add(self, name, model);
    }
SWIGINTERN FsgModel *FsgSet_get_fsg(FsgSet *self,char const *name){
        return fsg_set_get_fsg(self, name);
    }
SWIGINTERN FsgModel *FsgSet_select(FsgSet *self,char const *name){
        return fsg_set_select(self, name);
    }
SWIGINTERN FsgModel *FsgSet_remove_byname(FsgSet *self,char const *name){
        return fsg_set_remove_byname(self, name);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1hypstr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->hypstr);
    if (arg2) {
      arg1->hypstr = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->hypstr, (const char *)arg2);
    } else {
      arg1->hypstr = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1hypstr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  result = (char *) ((arg1)->hypstr);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1uttid_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->uttid);
    if (arg2) {
      arg1->uttid = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->uttid, (const char *)arg2);
    } else {
      arg1->uttid = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1uttid_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  result = (char *) ((arg1)->uttid);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1bestScore_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->best_score = arg2;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Hypothesis_1bestScore_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Hypothesis **)&jarg1; 
  result = (int) ((arg1)->best_score);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Hypothesis(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  Hypothesis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (Hypothesis *)new_Hypothesis((char const *)arg1,(char const *)arg2,arg3);
  *(Hypothesis **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1Hypothesis(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Hypothesis *arg1 = (Hypothesis *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Hypothesis **)&jarg1; 
  delete_Hypothesis(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1ptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  ps_seg_t *arg2 = (ps_seg_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  arg2 = *(ps_seg_t **)&jarg2; 
  if (arg1) (arg1)->ptr = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1ptr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  ps_seg_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result = (ps_seg_t *) ((arg1)->ptr);
  *(ps_seg_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1word_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->word);
    if (arg2) {
      arg1->word = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->word, (const char *)arg2);
    } else {
      arg1->word = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1word_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result = (char *) ((arg1)->word);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1ascr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  int32 arg2 ;
  int32 *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->ascr = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1ascr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result =  ((arg1)->ascr);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1lscr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  int32 arg2 ;
  int32 *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lscr = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1lscr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result =  ((arg1)->lscr);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1lback_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  int32 arg2 ;
  int32 *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lback = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1lback_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result =  ((arg1)->lback);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1startFrame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->start_frame = arg2;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1startFrame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result = (int) ((arg1)->start_frame);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1endFrame_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Segment *arg1 = (Segment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->end_frame = arg2;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Segment_1endFrame_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Segment *arg1 = (Segment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Segment **)&jarg1; 
  result = (int) ((arg1)->end_frame);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Segment(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  ps_seg_t *arg1 = (ps_seg_t *) 0 ;
  Segment *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ps_seg_t **)&jarg1; 
  result = (Segment *)new_Segment(arg1);
  *(Segment **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1Segment(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Segment *arg1 = (Segment *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Segment **)&jarg1; 
  delete_Segment(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_NBest_1ptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  NBest *arg1 = (NBest *) 0 ;
  ps_nbest_t *arg2 = (ps_nbest_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NBest **)&jarg1; 
  arg2 = *(ps_nbest_t **)&jarg2; 
  if (arg1) (arg1)->ptr = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_NBest_1ptr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NBest *arg1 = (NBest *) 0 ;
  ps_nbest_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NBest **)&jarg1; 
  result = (ps_nbest_t *) ((arg1)->ptr);
  *(ps_nbest_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1NBest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  ps_nbest_t *arg1 = (ps_nbest_t *) 0 ;
  NBest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ps_nbest_t **)&jarg1; 
  result = (NBest *)new_NBest(arg1);
  *(NBest **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1NBest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  NBest *arg1 = (NBest *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(NBest **)&jarg1; 
  delete_NBest(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_NBest_1hyp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NBest *arg1 = (NBest *) 0 ;
  Hypothesis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NBest **)&jarg1; 
  result = (Hypothesis *)NBest_hyp(arg1);
  *(Hypothesis **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_NBest_1seg(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NBest *arg1 = (NBest *) 0 ;
  Segment *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NBest **)&jarg1; 
  result = (Segment *)NBest_seg(arg1);
  *(Segment **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Decoder_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Decoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Decoder *)new_Decoder__SWIG_0();
  *(Decoder **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Decoder_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  Decoder *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  result = (Decoder *)new_Decoder__SWIG_1(arg1);
  *(Decoder **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1Decoder(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Decoder *arg1 = (Decoder *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Decoder **)&jarg1; 
  delete_Decoder(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1reinit(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Decoder *arg1 = (Decoder *) 0 ;
  Config *arg2 = (Config *) 0 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = *(Config **)&jarg2; 
  Decoder_reinit(arg1,arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_reinit returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1loadDict(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4) {
  Decoder *arg1 = (Decoder *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int *arg5 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg5 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return ;
  }
  Decoder_load_dict(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
  {
    if (*arg5 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_loadDict returned %d", *arg5);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1saveDict(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  Decoder *arg1 = (Decoder *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int *arg4 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg4 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  Decoder_save_dict(arg1,(char const *)arg2,(char const *)arg3,arg4);
  {
    if (*arg4 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_saveDict returned %d", *arg4);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1addWord(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jint jarg4) {
  Decoder *arg1 = (Decoder *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  int *arg5 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg5 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  arg4 = (int)jarg4; 
  Decoder_add_word(arg1,(char const *)arg2,(char const *)arg3,arg4,arg5);
  {
    if (*arg5 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_addWord returned %d", *arg5);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getLattice(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  Lattice *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (Lattice *)Decoder_get_lattice(arg1);
  *(Lattice **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getConfig(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  Config *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (Config *)Decoder_get_config(arg1);
  *(Config **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1defaultConfig(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Config *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Config *)Decoder_default_config();
  *(Config **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1startUtt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Decoder *arg1 = (Decoder *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  Decoder_start_utt(arg1,(char const *)arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_startUtt returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getUttid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (char *)Decoder_get_uttid(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1endUtt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Decoder *arg1 = (Decoder *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg2 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  Decoder_end_utt(arg1,arg2);
  {
    if (*arg2 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_endUtt returned %d", *arg2);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1processRaw(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshortArray jarg2, jboolean jarg4, jboolean jarg5) {
  jint jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  bool arg4 ;
  bool arg5 ;
  int *arg6 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg6 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  {
    arg2 = (short const *) (*jenv)->GetShortArrayElements(jenv, jarg2, NULL);
    arg3 = (*jenv)->GetArrayLength(jenv, jarg2);
  }
  arg4 = jarg4 ? true : false; 
  arg5 = jarg5 ? true : false; 
  result = (int)Decoder_process_raw(arg1,(void const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  {
    if (*arg6 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_processRaw returned %d", *arg6);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1decodeRaw(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = *(FILE **)&jarg2; 
  result = (int)Decoder_decode_raw(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "Decoder_decodeRaw returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1hyp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  Hypothesis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (Hypothesis *)Decoder_hyp(arg1);
  *(Hypothesis **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1nbest(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  NBest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (NBest *)Decoder_nbest(arg1);
  *(NBest **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1seg(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  Segment *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (Segment *)Decoder_seg(arg1);
  *(Segment **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getFe(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  FrontEnd *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (FrontEnd *)Decoder_get_fe(arg1);
  *(FrontEnd **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getFeat(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  Feature *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (Feature *)Decoder_get_feat(arg1);
  *(Feature **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getLmset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  NGramModelSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (NGramModelSet *)Decoder_get_lmset(arg1);
  *(NGramModelSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1updateLmset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  NGramModelSet *arg2 = (NGramModelSet *) 0 ;
  NGramModelSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = *(NGramModelSet **)&jarg2; 
  result = (NGramModelSet *)Decoder_update_lmset(arg1,arg2);
  *(NGramModelSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getFsgset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  FsgSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (FsgSet *)Decoder_get_fsgset(arg1);
  *(FsgSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1updateFsgset(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  FsgSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (FsgSet *)Decoder_update_fsgset(arg1);
  *(FsgSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1getLogmath(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  LogMath *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (LogMath *)Decoder_get_logmath(arg1);
  *(LogMath **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Decoder_1nFrames(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  result = (int)Decoder_n_frames(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Lattice_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  Lattice *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (Lattice *)new_Lattice__SWIG_0((char const *)arg1);
  *(Lattice **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1Lattice_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Decoder *arg1 = (Decoder *) 0 ;
  char *arg2 = (char *) 0 ;
  Lattice *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Decoder **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (Lattice *)new_Lattice__SWIG_1(arg1,arg2);
  *(Lattice **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1Lattice(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Lattice *arg1 = (Lattice *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Lattice **)&jarg1; 
  delete_Lattice(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Lattice_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Lattice *arg1 = (Lattice *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(Lattice **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  Lattice_write(arg1,(char const *)arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "Lattice_write returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_Lattice_1writeHtk(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Lattice *arg1 = (Lattice *) 0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(Lattice **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  Lattice_write_htk(arg1,(char const *)arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "Lattice_writeHtk returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_new_1FsgSet(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  FsgSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (FsgSet *)new_FsgSet(arg1);
  *(FsgSet **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_delete_1FsgSet(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FsgSet *arg1 = (FsgSet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FsgSet **)&jarg1; 
  delete_FsgSet(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_FsgSet_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_) {
  jlong jresult = 0 ;
  FsgSet *arg1 = (FsgSet *) 0 ;
  char *arg2 = (char *) 0 ;
  FsgModel *arg3 = (FsgModel *) 0 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(FsgSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(FsgModel **)&jarg3; 
  result = (FsgModel *)FsgSet_add(arg1,(char const *)arg2,arg3);
  *(FsgModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_FsgSet_1getFsg(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  FsgSet *arg1 = (FsgSet *) 0 ;
  char *arg2 = (char *) 0 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (FsgModel *)FsgSet_get_fsg(arg1,(char const *)arg2);
  *(FsgModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_FsgSet_1select(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  FsgSet *arg1 = (FsgSet *) 0 ;
  char *arg2 = (char *) 0 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (FsgModel *)FsgSet_select(arg1,(char const *)arg2);
  *(FsgModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_pocketsphinxJNI_FsgSet_1removeByname(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  FsgSet *arg1 = (FsgSet *) 0 ;
  char *arg2 = (char *) 0 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (FsgModel *)FsgSet_remove_byname(arg1,(char const *)arg2);
  *(FsgModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


#ifdef __cplusplus
}
#endif

