/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#include <sphinxbase/cmd_ln.h>
#include <sphinxbase/err.h>
#include <sphinxbase/fe.h>
#include <sphinxbase/feat.h>
#include <sphinxbase/jsgf.h>
#include <sphinxbase/ngram_model.h>

typedef int bool;
#define false 0
#define true 1

typedef cmd_ln_t Config;
typedef jsgf_t Jsgf;
typedef jsgf_rule_t JsgfRule;
typedef feat_t Feature;
typedef fe_t FrontEnd;
typedef fsg_model_t FsgModel;
typedef logmath_t LogMath;
typedef ngram_model_t NGramModel;
typedef ngram_model_t NGramModelSet;


#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1 
#define  SWIG_IOError        	   -2 
#define  SWIG_RuntimeError   	   -3 
#define  SWIG_IndexError     	   -4 
#define  SWIG_TypeError      	   -5 
#define  SWIG_DivisionByZero 	   -6 
#define  SWIG_OverflowError  	   -7 
#define  SWIG_SyntaxError    	   -8 
#define  SWIG_ValueError     	   -9 
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12 
#define  SWIG_NullReferenceError   -13




ngram_model_t * next_NGramModelSetIterator(ngram_model_set_iter_t *iter)
{
    const char *name;
    return ngram_model_set_iter_model(iter, &name);
}


SWIGINTERN void SWIG_JavaException(JNIEnv *jenv, int code, const char *msg) {
  SWIG_JavaExceptionCodes exception_code = SWIG_JavaUnknownError;
  switch(code) {
  case SWIG_MemoryError:
    exception_code = SWIG_JavaOutOfMemoryError;
    break;
  case SWIG_IOError:
    exception_code = SWIG_JavaIOException;
    break;
  case SWIG_SystemError:
  case SWIG_RuntimeError:
    exception_code = SWIG_JavaRuntimeException;
    break;
  case SWIG_OverflowError:
  case SWIG_IndexError:
    exception_code = SWIG_JavaIndexOutOfBoundsException;
    break;
  case SWIG_DivisionByZero:
    exception_code = SWIG_JavaArithmeticException;
    break;
  case SWIG_SyntaxError:
  case SWIG_ValueError:
  case SWIG_TypeError:
    exception_code = SWIG_JavaIllegalArgumentException;
    break;
  case SWIG_UnknownError:
  default:
    exception_code = SWIG_JavaUnknownError;
    break;
  }
  SWIG_JavaThrowException(jenv, exception_code, msg);
}


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* signed char[] support */
static int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetByteArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (signed char*) calloc(sz, sizeof(signed char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  (*jenv)->ReleaseByteArrayElements(jenv, input, jarr, 0);
}

static jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = (*jenv)->NewByteArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetByteArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  (*jenv)->ReleaseByteArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
static int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned char*) calloc(sz, sizeof(unsigned char)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* short[] support */
static int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetShortArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (short*) calloc(sz, sizeof(short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  (*jenv)->ReleaseShortArrayElements(jenv, input, jarr, 0);
}

static jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = (*jenv)->NewShortArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetShortArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  (*jenv)->ReleaseShortArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
static int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned short*) calloc(sz, sizeof(unsigned short)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* int[] support */
static int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (int*) calloc(sz, sizeof(int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
static int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned int*) calloc(sz, sizeof(unsigned int)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* long[] support */
static int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetIntArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (long*) calloc(sz, sizeof(long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  (*jenv)->ReleaseIntArrayElements(jenv, input, jarr, 0);
}

static jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = (*jenv)->NewIntArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetIntArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  (*jenv)->ReleaseIntArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
static int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (unsigned long*) calloc(sz, sizeof(unsigned long)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
static int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetLongArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (jlong*) calloc(sz, sizeof(jlong)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  (*jenv)->ReleaseLongArrayElements(jenv, input, jarr, 0);
}

static jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = (*jenv)->NewLongArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetLongArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  (*jenv)->ReleaseLongArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* float[] support */
static int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetFloatArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (float*) calloc(sz, sizeof(float)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, input, jarr, 0);
}

static jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = (*jenv)->NewFloatArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetFloatArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  (*jenv)->ReleaseFloatArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


/* double[] support */
static int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = (*jenv)->GetArrayLength(jenv, input);
  *jarr = (*jenv)->GetDoubleArrayElements(jenv, input, 0);
  if (!*jarr)
    return 0; 
  *carr = (double*) calloc(sz, sizeof(double)); 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

static void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = (*jenv)->GetArrayLength(jenv, input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, input, jarr, 0);
}

static jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = (*jenv)->NewDoubleArray(jenv, sz);
  if (!jresult)
    return NULL;
  arr = (*jenv)->GetDoubleArrayElements(jenv, jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  (*jenv)->ReleaseDoubleArrayElements(jenv, jresult, arr, 0);
  return jresult;
}


#endif

SWIGINTERN Config *new_Config(){
	return NULL;
    }
SWIGINTERN void delete_Config(Config *self){
        cmd_ln_free_r(self);
    }
SWIGINTERN void Config_set_boolean(Config *self,char const *key,bool val){
        cmd_ln_set_boolean_r(self, key, val);
    }
SWIGINTERN void Config_set_int(Config *self,char const *key,int val){
        cmd_ln_set_int_r(self, key, val);
    }
SWIGINTERN void Config_set_float(Config *self,char const *key,double val){
        cmd_ln_set_float_r(self, key, val);
    }
SWIGINTERN void Config_set_string(Config *self,char const *key,char const *val){
        cmd_ln_set_str_r(self, key, val);
    }
SWIGINTERN bool Config_exists(Config *self,char const *key){
        return cmd_ln_exists_r(self, key);
    }
SWIGINTERN bool Config_get_boolean(Config *self,char const *key){
        return cmd_ln_boolean_r(self, key);
    }
SWIGINTERN int Config_get_int(Config *self,char const *key){
        return cmd_ln_int_r(self, key);
    }
SWIGINTERN double Config_get_float(Config *self,char const *key){
        return cmd_ln_float_r(self, key);
    }
SWIGINTERN char const *Config_get_string(Config *self,char const *key){
        return cmd_ln_str_r(self, key);
    }
SWIGINTERN FrontEnd *new_FrontEnd(fe_t *ptr){
        return ptr;
    }
SWIGINTERN void delete_FrontEnd(FrontEnd *self){
        fe_free(self);
    }
SWIGINTERN int FrontEnd_output_size(FrontEnd *self){
        return fe_get_output_size(self);
    }
SWIGINTERN void FrontEnd_start_utt(FrontEnd *self,int *errcode){
        *errcode = fe_start_utt(self);
    }
SWIGINTERN int32 FrontEnd_process_utt(FrontEnd *self,int16 const *spch,size_t nsamps,mfcc_t ***cep_block,int *errcode){
        int32 nframes;
        *errcode = fe_process_utt(self, spch, nsamps, cep_block, &nframes);
        return nframes;
    }
SWIGINTERN int32 FrontEnd_end_utt(FrontEnd *self,mfcc_t *out_cepvector,int *errcode){
        int32 nframes;
        *errcode = fe_end_utt(self, out_cepvector, &nframes);
        return nframes;
    }
SWIGINTERN Feature *new_Feature(feat_t *ptr){
      return ptr;
    }
SWIGINTERN void delete_Feature(Feature *self){
        feat_free(self);
    }
SWIGINTERN FsgModel *new_FsgModel(fsg_model_t *ptr){
        return ptr;
    }
SWIGINTERN void delete_FsgModel(FsgModel *self){
        fsg_model_free(self);
    }
SWIGINTERN int FsgModel_word_id(FsgModel *self,char const *word){
        return fsg_model_word_id(self, word);
    }
SWIGINTERN int FsgModel_word_add(FsgModel *self,char const *word){
        return fsg_model_word_add(self, word);
    }
SWIGINTERN void FsgModel_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp,int32 wid){
        fsg_model_trans_add(self, src, dst, logp, wid);
    }
SWIGINTERN int32 FsgModel_null_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp){
        return fsg_model_null_trans_add(self, src, dst, logp);
    }
SWIGINTERN int32 FsgModel_tag_trans_add(FsgModel *self,int32 src,int32 dst,int32 logp,int32 wid){
        return fsg_model_tag_trans_add(self, src, dst, logp, wid);
    }
SWIGINTERN int FsgModel_add_silence(FsgModel *self,char const *silword,int state,int32 silprob){
        return fsg_model_add_silence(self, silword, state, silprob); 
    }
SWIGINTERN int FsgModel_add_alt(FsgModel *self,char const *baseword,char const *altword){
        return fsg_model_add_alt(self, baseword, altword);
    }
SWIGINTERN void FsgModel_write(FsgModel *self,FILE *file){
        fsg_model_write(self, file);
    }
SWIGINTERN void FsgModel_writefile(FsgModel *self,char const *path){
        fsg_model_writefile(self, path);
    }
SWIGINTERN Jsgf *new_Jsgf(char const *path){
        return jsgf_parse_file(path, NULL);
    }
SWIGINTERN void delete_Jsgf(Jsgf *self){
        jsgf_grammar_free(self);
    }
SWIGINTERN char const *Jsgf_name(Jsgf *self){
        return jsgf_grammar_name(self);
    }
SWIGINTERN JsgfRule *Jsgf_get_rule(Jsgf *self,char const *name){
        return jsgf_get_rule(self, name);
    }
SWIGINTERN FsgModel *Jsgf_build_fsg(Jsgf *self,JsgfRule *rule,LogMath *logmath,float lw){
        return jsgf_build_fsg(self, rule, logmath, lw);
    }
SWIGINTERN NGramModel *new_NGramModel(char const *path){
        return ngram_model_read(NULL, path, NGRAM_AUTO, logmath_init(1.001, 0, 0));
    }
SWIGINTERN void delete_NGramModel(NGramModel *self){
        ngram_model_free(self);
    }
SWIGINTERN void NGramModel_write(NGramModel *self,char const *path,ngram_file_type_t ftype,int *errcode){
        *errcode = ngram_model_write(self, path, ftype);
    }
SWIGINTERN ngram_file_type_t NGramModel_str_to_type(NGramModel *self,char const *str){
        return ngram_str_to_type(str);
    }
SWIGINTERN char const *NGramModel_type_to_str(NGramModel *self,int type){
        return ngram_type_to_str(type);
    }
SWIGINTERN void NGramModel_recode(NGramModel *self,char const *src,char const *dst,int *errcode){
        *errcode = ngram_model_recode(self, src, dst);
    }
SWIGINTERN void NGramModel_casefold(NGramModel *self,int kase,int *errcode){
        *errcode = ngram_model_casefold(self, kase);
    }
SWIGINTERN int32 NGramModel_size(NGramModel *self){
        return ngram_model_get_size(self);
    }
SWIGINTERN int32 NGramModel_add_word(NGramModel *self,char const *word,float32 weight){
        return ngram_model_add_word(self, word, weight);
    }
SWIGINTERN int32 NGramModel_add_class(NGramModel *self,char const *c,float32 w,char **words,float32 const *weights,int32 nwords){
        return ngram_model_add_class(self, c, w, words, weights, nwords);
    }

typedef struct {
  ngram_model_set_iter_t *ptr;
} NGramModelSetIterator;

SWIGINTERN NGramModelSetIterator *new_NGramModelSetIterator(ngram_model_set_iter_t *ptr){
    NGramModelSetIterator *iter = ckd_malloc(sizeof *iter);
    iter->ptr = ptr;
    return iter;
  }
SWIGINTERN void delete_NGramModelSetIterator(NGramModelSetIterator *self){
    ngram_model_set_iter_free(self->ptr);
    ckd_free(self);
  }
SWIGINTERN NGramModel *NGramModelSetIterator_next(NGramModelSetIterator *self){
    if (self->ptr) {
      NGramModel *value = next_NGramModelSetIterator(self->ptr);
      self->ptr = ngram_model_set_iter_next(self->ptr);
      return value;
    } else {
      return NULL;
    }
  }
SWIGINTERN NGramModelSetIterator *NGramModelSet___iter__(NGramModelSet *self){
    return new_NGramModelSetIterator(ngram_model_set_iter(self));
  }
SWIGINTERN NGramModelSet *new_NGramModelSet(char const *path){
        return ngram_model_set_read(NULL, path, logmath_init(1.001, 0, 0));
    }
SWIGINTERN void delete_NGramModelSet(NGramModelSet *self){
        ngram_model_free(self);
    }
SWIGINTERN int32 NGramModelSet_count(NGramModelSet *self){
        return ngram_model_set_count(self);
    }
SWIGINTERN NGramModel *NGramModelSet_add(NGramModelSet *self,NGramModel *model,char const *name,float weight,int reuse_widmap){
        return ngram_model_set_add(self, model, name, weight, reuse_widmap);
    }
SWIGINTERN NGramModel *NGramModelSet_select(NGramModelSet *self,char const *name){
        return ngram_model_set_select(self, name);
    }
SWIGINTERN NGramModel *NGramModelSet_lookup(NGramModelSet *self,char const *name){
        return ngram_model_set_lookup(self, name);
    }
SWIGINTERN char const *NGramModelSet_current(NGramModelSet *self){
        return ngram_model_set_current(self);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1Config(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Config *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Config *)new_Config();
  *(Config **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1Config(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Config *arg1 = (Config *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Config **)&jarg1; 
  delete_Config(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1setBoolean(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = jarg3 ? true : false; 
  Config_set_boolean(arg1,(char const *)arg2,arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1setInt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = (int)jarg3; 
  Config_set_int(arg1,(char const *)arg2,arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1setFloat(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jdouble jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = (double)jarg3; 
  Config_set_float(arg1,(char const *)arg2,arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1setString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  Config_set_string(arg1,(char const *)arg2,(char const *)arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT jboolean JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1exists(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jboolean jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)Config_exists(arg1,(char const *)arg2);
  jresult = (jboolean)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1getBoolean(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jboolean jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)Config_get_boolean(arg1,(char const *)arg2);
  jresult = (jboolean)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1getInt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)Config_get_int(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1getFloat(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jdouble jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (double)Config_get_float(arg1,(char const *)arg2);
  jresult = (jdouble)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Config_1getString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jstring jresult = 0 ;
  Config *arg1 = (Config *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Config **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (char *)Config_get_string(arg1,(char const *)arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1FrontEnd(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  fe_t *arg1 = (fe_t *) 0 ;
  FrontEnd *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(fe_t **)&jarg1; 
  result = (FrontEnd *)new_FrontEnd(arg1);
  *(FrontEnd **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1FrontEnd(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FrontEnd **)&jarg1; 
  delete_FrontEnd(arg1);
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FrontEnd_1outputSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FrontEnd **)&jarg1; 
  result = (int)FrontEnd_output_size(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FrontEnd_1startUtt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg2 = &errcode;
  (void)jarg1_;
  arg1 = *(FrontEnd **)&jarg1; 
  FrontEnd_start_utt(arg1,arg2);
  {
    if (*arg2 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_startUtt returned %d", *arg2);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FrontEnd_1processUtt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  int16 *arg2 = (int16 *) 0 ;
  size_t arg3 ;
  mfcc_t ***arg4 = (mfcc_t ***) 0 ;
  int *arg5 = (int *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg5 = &errcode;
  (void)jarg1_;
  arg1 = *(FrontEnd **)&jarg1; 
  arg2 = *(int16 **)&jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(mfcc_t ****)&jarg4; 
  result = FrontEnd_process_utt(arg1,(int16 const *)arg2,arg3,arg4,arg5);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  {
    if (*arg5 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_processUtt returned %d", *arg5);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FrontEnd_1endUtt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  FrontEnd *arg1 = (FrontEnd *) 0 ;
  mfcc_t *arg2 = (mfcc_t *) 0 ;
  int *arg3 = (int *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(FrontEnd **)&jarg1; 
  arg2 = *(mfcc_t **)&jarg2; 
  result = FrontEnd_end_utt(arg1,arg2,arg3);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "FrontEnd_endUtt returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return 0; 
      };
    }
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1Feature(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  feat_t *arg1 = (feat_t *) 0 ;
  Feature *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(feat_t **)&jarg1; 
  result = (Feature *)new_Feature(arg1);
  *(Feature **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1Feature(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Feature *arg1 = (Feature *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Feature **)&jarg1; 
  delete_Feature(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1FsgModel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  fsg_model_t *arg1 = (fsg_model_t *) 0 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(fsg_model_t **)&jarg1; 
  result = (FsgModel *)new_FsgModel(arg1);
  *(FsgModel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1FsgModel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FsgModel **)&jarg1; 
  delete_FsgModel(arg1);
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1wordId(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)FsgModel_word_id(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1wordAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)FsgModel_word_add(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1transAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 arg5 ;
  int32 *argp2 ;
  int32 *argp3 ;
  int32 *argp4 ;
  int32 *argp5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg2 = *argp2; 
  argp3 = *(int32 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg3 = *argp3; 
  argp4 = *(int32 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg4 = *argp4; 
  argp5 = *(int32 **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return ;
  }
  arg5 = *argp5; 
  FsgModel_trans_add(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1nullTransAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 *argp2 ;
  int32 *argp3 ;
  int32 *argp4 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(int32 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(int32 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg4 = *argp4; 
  result = FsgModel_null_trans_add(arg1,arg2,arg3,arg4);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1tagTransAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  int32 arg2 ;
  int32 arg3 ;
  int32 arg4 ;
  int32 arg5 ;
  int32 *argp2 ;
  int32 *argp3 ;
  int32 *argp4 ;
  int32 *argp5 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  argp2 = *(int32 **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(int32 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(int32 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg4 = *argp4; 
  argp5 = *(int32 **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg5 = *argp5; 
  result = FsgModel_tag_trans_add(arg1,arg2,arg3,arg4,arg5);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1addSilence(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3, jlong jarg4) {
  jint jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int32 arg4 ;
  int32 *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  argp4 = *(int32 **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg4 = *argp4; 
  result = (int)FsgModel_add_silence(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1addAlt(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)FsgModel_add_alt(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = *(FILE **)&jarg2; 
  FsgModel_write(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_FsgModel_1writefile(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  FsgModel *arg1 = (FsgModel *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FsgModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  FsgModel_writefile(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1Jsgf(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  Jsgf *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (Jsgf *)new_Jsgf((char const *)arg1);
  *(Jsgf **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1Jsgf(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Jsgf *arg1 = (Jsgf *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Jsgf **)&jarg1; 
  delete_Jsgf(arg1);
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Jsgf_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Jsgf **)&jarg1; 
  result = (char *)Jsgf_name(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Jsgf_1getRule(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  char *arg2 = (char *) 0 ;
  JsgfRule *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Jsgf **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (JsgfRule *)Jsgf_get_rule(arg1,(char const *)arg2);
  *(JsgfRule **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_Jsgf_1buildFsg(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jfloat jarg4) {
  jlong jresult = 0 ;
  Jsgf *arg1 = (Jsgf *) 0 ;
  JsgfRule *arg2 = (JsgfRule *) 0 ;
  LogMath *arg3 = (LogMath *) 0 ;
  float arg4 ;
  FsgModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Jsgf **)&jarg1; 
  arg2 = *(JsgfRule **)&jarg2; 
  arg3 = *(LogMath **)&jarg3; 
  arg4 = (float)jarg4; 
  result = (FsgModel *)Jsgf_build_fsg(arg1,arg2,arg3,arg4);
  *(FsgModel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1NGramModel(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (NGramModel *)new_NGramModel((char const *)arg1);
  *(NGramModel **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1NGramModel(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(NGramModel **)&jarg1; 
  delete_NGramModel(arg1);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  ngram_file_type_t arg3 ;
  int *arg4 = (int *) 0 ;
  ngram_file_type_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg4 = &errcode;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  argp3 = *(ngram_file_type_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null ngram_file_type_t");
    return ;
  }
  arg3 = *argp3; 
  NGramModel_write(arg1,(char const *)arg2,arg3,arg4);
  {
    if (*arg4 < 0) {
      char buf[64];
      sprintf(buf, "NGramModel_write returned %d", *arg4);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1strToType(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  ngram_file_type_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = NGramModel_str_to_type(arg1,(char const *)arg2);
  {
    ngram_file_type_t * resultptr = (ngram_file_type_t *) malloc(sizeof(ngram_file_type_t));
    memmove(resultptr, &result, sizeof(ngram_file_type_t));
    *(ngram_file_type_t **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1typeToStr(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)NGramModel_type_to_str(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1recode(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int *arg4 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg4 = &errcode;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  NGramModel_recode(arg1,(char const *)arg2,(char const *)arg3,arg4);
  {
    if (*arg4 < 0) {
      char buf[64];
      sprintf(buf, "NGramModel_recode returned %d", *arg4);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1casefold(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  NGramModel *arg1 = (NGramModel *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  int errcode;
  arg3 = &errcode;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = (int)jarg2; 
  NGramModel_casefold(arg1,arg2,arg3);
  {
    if (*arg3 < 0) {
      char buf[64];
      sprintf(buf, "NGramModel_casefold returned %d", *arg3);
      {
        SWIG_JavaException(jenv, SWIG_RuntimeError, buf); return ; 
      };
    }
  }
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  result = NGramModel_size(arg1);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1addWord(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  float32 arg3 ;
  float32 *argp3 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(float32 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null float32");
    return 0;
  }
  arg3 = *argp3; 
  result = NGramModel_add_word(arg1,(char const *)arg2,arg3);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModel_1addClass(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  NGramModel *arg1 = (NGramModel *) 0 ;
  char *arg2 = (char *) 0 ;
  float32 arg3 ;
  char **arg4 = (char **) 0 ;
  float32 *arg5 = (float32 *) 0 ;
  int32 arg6 ;
  float32 *argp3 ;
  int32 *argp6 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModel **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(float32 **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null float32");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(char ***)&jarg4; 
  arg5 = *(float32 **)&jarg5; 
  argp6 = *(int32 **)&jarg6; 
  if (!argp6) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int32");
    return 0;
  }
  arg6 = *argp6; 
  result = NGramModel_add_class(arg1,(char const *)arg2,arg3,arg4,(float32 const *)arg5,arg6);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSetIterator_1ptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  ngram_model_set_iter_t *arg2 = (ngram_model_set_iter_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSetIterator **)&jarg1; 
  arg2 = *(ngram_model_set_iter_t **)&jarg2; 
  if (arg1) (arg1)->ptr = arg2;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSetIterator_1ptr_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  ngram_model_set_iter_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSetIterator **)&jarg1; 
  result = (ngram_model_set_iter_t *) ((arg1)->ptr);
  *(ngram_model_set_iter_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1NGramModelSetIterator(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  ngram_model_set_iter_t *arg1 = (ngram_model_set_iter_t *) 0 ;
  NGramModelSetIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ngram_model_set_iter_t **)&jarg1; 
  result = (NGramModelSetIterator *)new_NGramModelSetIterator(arg1);
  *(NGramModelSetIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1NGramModelSetIterator(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(NGramModelSetIterator **)&jarg1; 
  delete_NGramModelSetIterator(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSetIterator_1next(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NGramModelSetIterator *arg1 = (NGramModelSetIterator *) 0 ;
  NGramModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSetIterator **)&jarg1; 
  result = (NGramModel *)NGramModelSetIterator_next(arg1);
  *(NGramModel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1iter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  NGramModelSetIterator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSet **)&jarg1; 
  result = (NGramModelSetIterator *)NGramModelSet___iter__(arg1);
  *(NGramModelSetIterator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_new_1NGramModelSet(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  NGramModelSet *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (NGramModelSet *)new_NGramModelSet((char const *)arg1);
  *(NGramModelSet **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_delete_1NGramModelSet(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(NGramModelSet **)&jarg1; 
  delete_NGramModelSet(arg1);
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1count(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  int32 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSet **)&jarg1; 
  result = NGramModelSet_count(arg1);
  {
    int32 * resultptr = (int32 *) malloc(sizeof(int32));
    memmove(resultptr, &result, sizeof(int32));
    *(int32 **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jfloat jarg4, jint jarg5) {
  jlong jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  NGramModel *arg2 = (NGramModel *) 0 ;
  char *arg3 = (char *) 0 ;
  float arg4 ;
  int arg5 ;
  NGramModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(NGramModelSet **)&jarg1; 
  arg2 = *(NGramModel **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (float)jarg4; 
  arg5 = (int)jarg5; 
  result = (NGramModel *)NGramModelSet_add(arg1,arg2,(char const *)arg3,arg4,arg5);
  *(NGramModel **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1select(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *arg2 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (NGramModel *)NGramModelSet_select(arg1,(char const *)arg2);
  *(NGramModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1lookup(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *arg2 = (char *) 0 ;
  NGramModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSet **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (NGramModel *)NGramModelSet_lookup(arg1,(char const *)arg2);
  *(NGramModel **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_NGramModelSet_1current(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  NGramModelSet *arg1 = (NGramModelSet *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(NGramModelSet **)&jarg1; 
  result = (char *)NGramModelSet_current(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_edu_cmu_pocketsphinx_sphinxbaseJNI_setLogFile(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)err_set_logfile((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


#ifdef __cplusplus
}
#endif

