/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Config {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sphinxbaseJNI.delete_Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Config() {
    this(sphinxbaseJNI.new_Config(), true);
  }

  public void setBoolean(String key, boolean val) {
    sphinxbaseJNI.Config_setBoolean(swigCPtr, this, key, val);
  }

  public void setInt(String key, int val) {
    sphinxbaseJNI.Config_setInt(swigCPtr, this, key, val);
  }

  public void setFloat(String key, double val) {
    sphinxbaseJNI.Config_setFloat(swigCPtr, this, key, val);
  }

  public void setString(String key, String val) {
    sphinxbaseJNI.Config_setString(swigCPtr, this, key, val);
  }

  public boolean exists(String key) {
    return sphinxbaseJNI.Config_exists(swigCPtr, this, key);
  }

  public boolean getBoolean(String key) {
    return sphinxbaseJNI.Config_getBoolean(swigCPtr, this, key);
  }

  public int getInt(String key) {
    return sphinxbaseJNI.Config_getInt(swigCPtr, this, key);
  }

  public double getFloat(String key) {
    return sphinxbaseJNI.Config_getFloat(swigCPtr, this, key);
  }

  public String getString(String key) {
    return sphinxbaseJNI.Config_getString(swigCPtr, this, key);
  }

}
