/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Decoder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Decoder() {
    this(pocketsphinxJNI.new_Decoder__SWIG_0(), true);
  }

  public Decoder(Config c) {
    this(pocketsphinxJNI.new_Decoder__SWIG_1(Config.getCPtr(c), c), true);
  }

  public void reinit(Config config) {
    pocketsphinxJNI.Decoder_reinit(swigCPtr, this, Config.getCPtr(config), config);
  }

  public void loadDict(String fdict, String ffilter, String format) {
    pocketsphinxJNI.Decoder_loadDict(swigCPtr, this, fdict, ffilter, format);
  }

  public void saveDict(String dictfile, String format) {
    pocketsphinxJNI.Decoder_saveDict(swigCPtr, this, dictfile, format);
  }

  public void addWord(String word, String phones, int update) {
    pocketsphinxJNI.Decoder_addWord(swigCPtr, this, word, phones, update);
  }

  public Lattice getLattice() {
    long cPtr = pocketsphinxJNI.Decoder_getLattice(swigCPtr, this);
    return (cPtr == 0) ? null : new Lattice(cPtr, false);
  }

  public Config getConfig() {
    long cPtr = pocketsphinxJNI.Decoder_getConfig(swigCPtr, this);
    return (cPtr == 0) ? null : new Config(cPtr, false);
  }

  public static Config defaultConfig() {
    long cPtr = pocketsphinxJNI.Decoder_defaultConfig();
    return (cPtr == 0) ? null : new Config(cPtr, false);
  }

  public void startUtt(String uttid) {
    pocketsphinxJNI.Decoder_startUtt(swigCPtr, this, uttid);
  }

  public String getUttid() {
    return pocketsphinxJNI.Decoder_getUttid(swigCPtr, this);
  }

  public void endUtt() {
    pocketsphinxJNI.Decoder_endUtt(swigCPtr, this);
  }

  public int processRaw(short[] SDATA, boolean no_search, boolean full_utt) {
    return pocketsphinxJNI.Decoder_processRaw(swigCPtr, this, SDATA, no_search, full_utt);
  }

  public int decodeRaw(SWIGTYPE_p_FILE f) {
    return pocketsphinxJNI.Decoder_decodeRaw(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(f));
  }

  public Hypothesis hyp() {
    long cPtr = pocketsphinxJNI.Decoder_hyp(swigCPtr, this);
    return (cPtr == 0) ? null : new Hypothesis(cPtr, false);
  }

  public NBest nbest() {
    long cPtr = pocketsphinxJNI.Decoder_nbest(swigCPtr, this);
    return (cPtr == 0) ? null : new NBest(cPtr, false);
  }

  public Segment seg() {
    long cPtr = pocketsphinxJNI.Decoder_seg(swigCPtr, this);
    return (cPtr == 0) ? null : new Segment(cPtr, false);
  }

  public FrontEnd getFe() {
    long cPtr = pocketsphinxJNI.Decoder_getFe(swigCPtr, this);
    return (cPtr == 0) ? null : new FrontEnd(cPtr, false);
  }

  public Feature getFeat() {
    long cPtr = pocketsphinxJNI.Decoder_getFeat(swigCPtr, this);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public NGramModelSet getLmset() {
    long cPtr = pocketsphinxJNI.Decoder_getLmset(swigCPtr, this);
    return (cPtr == 0) ? null : new NGramModelSet(cPtr, false);
  }

  public NGramModelSet updateLmset(NGramModelSet lm_set) {
    long cPtr = pocketsphinxJNI.Decoder_updateLmset(swigCPtr, this, NGramModelSet.getCPtr(lm_set), lm_set);
    return (cPtr == 0) ? null : new NGramModelSet(cPtr, false);
  }

  public FsgSet getFsgset() {
    long cPtr = pocketsphinxJNI.Decoder_getFsgset(swigCPtr, this);
    return (cPtr == 0) ? null : new FsgSet(cPtr, false);
  }

  public FsgSet updateFsgset() {
    long cPtr = pocketsphinxJNI.Decoder_updateFsgset(swigCPtr, this);
    return (cPtr == 0) ? null : new FsgSet(cPtr, false);
  }

  public SWIGTYPE_p_LogMath getLogmath() {
    long cPtr = pocketsphinxJNI.Decoder_getLogmath(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_LogMath(cPtr, false);
  }

  public int nFrames() {
    return pocketsphinxJNI.Decoder_nFrames(swigCPtr, this);
  }

}
