/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class FrontEnd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FrontEnd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrontEnd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sphinxbaseJNI.delete_FrontEnd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FrontEnd(SWIGTYPE_p_fe_t ptr) {
    this(sphinxbaseJNI.new_FrontEnd(SWIGTYPE_p_fe_t.getCPtr(ptr)), true);
  }

  public int outputSize() {
    return sphinxbaseJNI.FrontEnd_outputSize(swigCPtr, this);
  }

  public void startUtt() {
    sphinxbaseJNI.FrontEnd_startUtt(swigCPtr, this);
  }

  public SWIGTYPE_p_int32 processUtt(SWIGTYPE_p_int16 spch, long nsamps, SWIGTYPE_p_p_p_mfcc_t cep_block) {
    return new SWIGTYPE_p_int32(sphinxbaseJNI.FrontEnd_processUtt(swigCPtr, this, SWIGTYPE_p_int16.getCPtr(spch), nsamps, SWIGTYPE_p_p_p_mfcc_t.getCPtr(cep_block)), true);
  }

  public SWIGTYPE_p_int32 endUtt(SWIGTYPE_p_mfcc_t out_cepvector) {
    return new SWIGTYPE_p_int32(sphinxbaseJNI.FrontEnd_endUtt(swigCPtr, this, SWIGTYPE_p_mfcc_t.getCPtr(out_cepvector)), true);
  }

}
