/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class FsgModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FsgModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FsgModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sphinxbaseJNI.delete_FsgModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FsgModel(SWIGTYPE_p_fsg_model_t ptr) {
    this(sphinxbaseJNI.new_FsgModel(SWIGTYPE_p_fsg_model_t.getCPtr(ptr)), true);
  }

  public int wordId(String word) {
    return sphinxbaseJNI.FsgModel_wordId(swigCPtr, this, word);
  }

  public int wordAdd(String word) {
    return sphinxbaseJNI.FsgModel_wordAdd(swigCPtr, this, word);
  }

  public void transAdd(SWIGTYPE_p_int32 src, SWIGTYPE_p_int32 dst, SWIGTYPE_p_int32 logp, SWIGTYPE_p_int32 wid) {
    sphinxbaseJNI.FsgModel_transAdd(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(src), SWIGTYPE_p_int32.getCPtr(dst), SWIGTYPE_p_int32.getCPtr(logp), SWIGTYPE_p_int32.getCPtr(wid));
  }

  public SWIGTYPE_p_int32 nullTransAdd(SWIGTYPE_p_int32 src, SWIGTYPE_p_int32 dst, SWIGTYPE_p_int32 logp) {
    return new SWIGTYPE_p_int32(sphinxbaseJNI.FsgModel_nullTransAdd(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(src), SWIGTYPE_p_int32.getCPtr(dst), SWIGTYPE_p_int32.getCPtr(logp)), true);
  }

  public SWIGTYPE_p_int32 tagTransAdd(SWIGTYPE_p_int32 src, SWIGTYPE_p_int32 dst, SWIGTYPE_p_int32 logp, SWIGTYPE_p_int32 wid) {
    return new SWIGTYPE_p_int32(sphinxbaseJNI.FsgModel_tagTransAdd(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(src), SWIGTYPE_p_int32.getCPtr(dst), SWIGTYPE_p_int32.getCPtr(logp), SWIGTYPE_p_int32.getCPtr(wid)), true);
  }

  public int addSilence(String silword, int state, SWIGTYPE_p_int32 silprob) {
    return sphinxbaseJNI.FsgModel_addSilence(swigCPtr, this, silword, state, SWIGTYPE_p_int32.getCPtr(silprob));
  }

  public int addAlt(String baseword, String altword) {
    return sphinxbaseJNI.FsgModel_addAlt(swigCPtr, this, baseword, altword);
  }

  public void write(SWIGTYPE_p_FILE file) {
    sphinxbaseJNI.FsgModel_write(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(file));
  }

  public void writefile(String path) {
    sphinxbaseJNI.FsgModel_writefile(swigCPtr, this, path);
  }

}
