/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class FsgSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FsgSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FsgSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_FsgSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FsgSet(SWIGTYPE_p_void ptr) {
    this(pocketsphinxJNI.new_FsgSet(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public FsgModel add(String name, FsgModel model) {
    long cPtr = pocketsphinxJNI.FsgSet_add(swigCPtr, this, name, FsgModel.getCPtr(model), model);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

  public FsgModel getFsg(String name) {
    long cPtr = pocketsphinxJNI.FsgSet_getFsg(swigCPtr, this, name);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

  public FsgModel select(String name) {
    long cPtr = pocketsphinxJNI.FsgSet_select(swigCPtr, this, name);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

  public FsgModel removeByname(String name) {
    long cPtr = pocketsphinxJNI.FsgSet_removeByname(swigCPtr, this, name);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

}
