/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Jsgf {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Jsgf(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Jsgf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sphinxbaseJNI.delete_Jsgf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Jsgf(String path) {
    this(sphinxbaseJNI.new_Jsgf(path), true);
  }

  public String name() {
    return sphinxbaseJNI.Jsgf_name(swigCPtr, this);
  }

  public SWIGTYPE_p_JsgfRule getRule(String name) {
    long cPtr = sphinxbaseJNI.Jsgf_getRule(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_JsgfRule(cPtr, false);
  }

  public FsgModel buildFsg(SWIGTYPE_p_JsgfRule rule, SWIGTYPE_p_LogMath logmath, float lw) {
    long cPtr = sphinxbaseJNI.Jsgf_buildFsg(swigCPtr, this, SWIGTYPE_p_JsgfRule.getCPtr(rule), SWIGTYPE_p_LogMath.getCPtr(logmath), lw);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

}
