/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Lattice {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Lattice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Lattice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_Lattice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Lattice(String path) {
    this(pocketsphinxJNI.new_Lattice__SWIG_0(path), true);
  }

  public Lattice(Decoder decoder, String path) {
    this(pocketsphinxJNI.new_Lattice__SWIG_1(Decoder.getCPtr(decoder), decoder, path), true);
  }

  public void write(String path) {
    pocketsphinxJNI.Lattice_write(swigCPtr, this, path);
  }

  public void writeHtk(String path) {
    pocketsphinxJNI.Lattice_writeHtk(swigCPtr, this, path);
  }

}
