/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class NGramModelSet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NGramModelSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NGramModelSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        sphinxbaseJNI.delete_NGramModelSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NGramModelSetIterator iter() {
    long cPtr = sphinxbaseJNI.NGramModelSet_iter(swigCPtr, this);
    return (cPtr == 0) ? null : new NGramModelSetIterator(cPtr, false);
  }

  public NGramModelSet(String path) {
    this(sphinxbaseJNI.new_NGramModelSet(path), true);
  }

  public SWIGTYPE_p_int32 count() {
    return new SWIGTYPE_p_int32(sphinxbaseJNI.NGramModelSet_count(swigCPtr, this), true);
  }

  public NGramModel add(NGramModel model, String name, float weight, int reuse_widmap) {
    long cPtr = sphinxbaseJNI.NGramModelSet_add(swigCPtr, this, NGramModel.getCPtr(model), model, name, weight, reuse_widmap);
    return (cPtr == 0) ? null : new NGramModel(cPtr, false);
  }

  public NGramModel select(String name) {
    long cPtr = sphinxbaseJNI.NGramModelSet_select(swigCPtr, this, name);
    return (cPtr == 0) ? null : new NGramModel(cPtr, false);
  }

  public NGramModel lookup(String name) {
    long cPtr = sphinxbaseJNI.NGramModelSet_lookup(swigCPtr, this, name);
    return (cPtr == 0) ? null : new NGramModel(cPtr, false);
  }

  public String current() {
    return sphinxbaseJNI.NGramModelSet_current(swigCPtr, this);
  }

}
