/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class pocketsphinxJNI {
  public final static native void Hypothesis_hypstr_set(long jarg1, Hypothesis jarg1_, String jarg2);
  public final static native String Hypothesis_hypstr_get(long jarg1, Hypothesis jarg1_);
  public final static native void Hypothesis_uttid_set(long jarg1, Hypothesis jarg1_, String jarg2);
  public final static native String Hypothesis_uttid_get(long jarg1, Hypothesis jarg1_);
  public final static native void Hypothesis_bestScore_set(long jarg1, Hypothesis jarg1_, int jarg2);
  public final static native int Hypothesis_bestScore_get(long jarg1, Hypothesis jarg1_);
  public final static native long new_Hypothesis(String jarg1, String jarg2, int jarg3);
  public final static native void delete_Hypothesis(long jarg1);
  public final static native void Segment_ptr_set(long jarg1, Segment jarg1_, long jarg2);
  public final static native long Segment_ptr_get(long jarg1, Segment jarg1_);
  public final static native void Segment_word_set(long jarg1, Segment jarg1_, String jarg2);
  public final static native String Segment_word_get(long jarg1, Segment jarg1_);
  public final static native void Segment_ascr_set(long jarg1, Segment jarg1_, long jarg2);
  public final static native long Segment_ascr_get(long jarg1, Segment jarg1_);
  public final static native void Segment_lscr_set(long jarg1, Segment jarg1_, long jarg2);
  public final static native long Segment_lscr_get(long jarg1, Segment jarg1_);
  public final static native void Segment_lback_set(long jarg1, Segment jarg1_, long jarg2);
  public final static native long Segment_lback_get(long jarg1, Segment jarg1_);
  public final static native void Segment_startFrame_set(long jarg1, Segment jarg1_, int jarg2);
  public final static native int Segment_startFrame_get(long jarg1, Segment jarg1_);
  public final static native void Segment_endFrame_set(long jarg1, Segment jarg1_, int jarg2);
  public final static native int Segment_endFrame_get(long jarg1, Segment jarg1_);
  public final static native long new_Segment(long jarg1);
  public final static native void delete_Segment(long jarg1);
  public final static native void NBest_ptr_set(long jarg1, NBest jarg1_, long jarg2);
  public final static native long NBest_ptr_get(long jarg1, NBest jarg1_);
  public final static native long new_NBest(long jarg1);
  public final static native void delete_NBest(long jarg1);
  public final static native long NBest_hyp(long jarg1, NBest jarg1_);
  public final static native long NBest_seg(long jarg1, NBest jarg1_);
  public final static native long new_Decoder__SWIG_0();
  public final static native long new_Decoder__SWIG_1(long jarg1, Config jarg1_);
  public final static native void delete_Decoder(long jarg1);
  public final static native void Decoder_reinit(long jarg1, Decoder jarg1_, long jarg2, Config jarg2_);
  public final static native void Decoder_loadDict(long jarg1, Decoder jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void Decoder_saveDict(long jarg1, Decoder jarg1_, String jarg2, String jarg3);
  public final static native void Decoder_addWord(long jarg1, Decoder jarg1_, String jarg2, String jarg3, int jarg4);
  public final static native long Decoder_getLattice(long jarg1, Decoder jarg1_);
  public final static native long Decoder_getConfig(long jarg1, Decoder jarg1_);
  public final static native long Decoder_defaultConfig();
  public final static native void Decoder_startUtt(long jarg1, Decoder jarg1_, String jarg2);
  public final static native String Decoder_getUttid(long jarg1, Decoder jarg1_);
  public final static native void Decoder_endUtt(long jarg1, Decoder jarg1_);
  public final static native int Decoder_processRaw(long jarg1, Decoder jarg1_, short[] jarg2, boolean jarg4, boolean jarg5);
  public final static native int Decoder_decodeRaw(long jarg1, Decoder jarg1_, long jarg2);
  public final static native long Decoder_hyp(long jarg1, Decoder jarg1_);
  public final static native long Decoder_nbest(long jarg1, Decoder jarg1_);
  public final static native long Decoder_seg(long jarg1, Decoder jarg1_);
  public final static native long Decoder_getFe(long jarg1, Decoder jarg1_);
  public final static native long Decoder_getFeat(long jarg1, Decoder jarg1_);
  public final static native long Decoder_getLmset(long jarg1, Decoder jarg1_);
  public final static native long Decoder_updateLmset(long jarg1, Decoder jarg1_, long jarg2, NGramModelSet jarg2_);
  public final static native long Decoder_getFsgset(long jarg1, Decoder jarg1_);
  public final static native long Decoder_updateFsgset(long jarg1, Decoder jarg1_);
  public final static native long Decoder_getLogmath(long jarg1, Decoder jarg1_);
  public final static native int Decoder_nFrames(long jarg1, Decoder jarg1_);
  public final static native long new_Lattice__SWIG_0(String jarg1);
  public final static native long new_Lattice__SWIG_1(long jarg1, Decoder jarg1_, String jarg2);
  public final static native void delete_Lattice(long jarg1);
  public final static native void Lattice_write(long jarg1, Lattice jarg1_, String jarg2);
  public final static native void Lattice_writeHtk(long jarg1, Lattice jarg1_, String jarg2);
  public final static native long new_FsgSet(long jarg1);
  public final static native void delete_FsgSet(long jarg1);
  public final static native long FsgSet_add(long jarg1, FsgSet jarg1_, String jarg2, long jarg3, FsgModel jarg3_);
  public final static native long FsgSet_getFsg(long jarg1, FsgSet jarg1_, String jarg2);
  public final static native long FsgSet_select(long jarg1, FsgSet jarg1_, String jarg2);
  public final static native long FsgSet_removeByname(long jarg1, FsgSet jarg1_, String jarg2);
}
