/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Segment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Segment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Segment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_Segment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPtr(SWIGTYPE_p_ps_seg_t value) {
    pocketsphinxJNI.Segment_ptr_set(swigCPtr, this, SWIGTYPE_p_ps_seg_t.getCPtr(value));
  }

  public SWIGTYPE_p_ps_seg_t getPtr() {
    long cPtr = pocketsphinxJNI.Segment_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ps_seg_t(cPtr, false);
  }

  public void setWord(String value) {
    pocketsphinxJNI.Segment_word_set(swigCPtr, this, value);
  }

  public String getWord() {
    return pocketsphinxJNI.Segment_word_get(swigCPtr, this);
  }

  public void setAscr(SWIGTYPE_p_int32 value) {
    pocketsphinxJNI.Segment_ascr_set(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(value));
  }

  public SWIGTYPE_p_int32 getAscr() {
    return new SWIGTYPE_p_int32(pocketsphinxJNI.Segment_ascr_get(swigCPtr, this), true);
  }

  public void setLscr(SWIGTYPE_p_int32 value) {
    pocketsphinxJNI.Segment_lscr_set(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(value));
  }

  public SWIGTYPE_p_int32 getLscr() {
    return new SWIGTYPE_p_int32(pocketsphinxJNI.Segment_lscr_get(swigCPtr, this), true);
  }

  public void setLback(SWIGTYPE_p_int32 value) {
    pocketsphinxJNI.Segment_lback_set(swigCPtr, this, SWIGTYPE_p_int32.getCPtr(value));
  }

  public SWIGTYPE_p_int32 getLback() {
    return new SWIGTYPE_p_int32(pocketsphinxJNI.Segment_lback_get(swigCPtr, this), true);
  }

  public void setStartFrame(int value) {
    pocketsphinxJNI.Segment_startFrame_set(swigCPtr, this, value);
  }

  public int getStartFrame() {
    return pocketsphinxJNI.Segment_startFrame_get(swigCPtr, this);
  }

  public void setEndFrame(int value) {
    pocketsphinxJNI.Segment_endFrame_set(swigCPtr, this, value);
  }

  public int getEndFrame() {
    return pocketsphinxJNI.Segment_endFrame_get(swigCPtr, this);
  }

  public Segment(SWIGTYPE_p_ps_seg_t ptr) {
    this(pocketsphinxJNI.new_Segment(SWIGTYPE_p_ps_seg_t.getCPtr(ptr)), true);
  }

}
