/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class sphinxbaseJNI {
  public final static native long new_Config();
  public final static native void delete_Config(long jarg1);
  public final static native void Config_setBoolean(long jarg1, Config jarg1_, String jarg2, boolean jarg3);
  public final static native void Config_setInt(long jarg1, Config jarg1_, String jarg2, int jarg3);
  public final static native void Config_setFloat(long jarg1, Config jarg1_, String jarg2, double jarg3);
  public final static native void Config_setString(long jarg1, Config jarg1_, String jarg2, String jarg3);
  public final static native boolean Config_exists(long jarg1, Config jarg1_, String jarg2);
  public final static native boolean Config_getBoolean(long jarg1, Config jarg1_, String jarg2);
  public final static native int Config_getInt(long jarg1, Config jarg1_, String jarg2);
  public final static native double Config_getFloat(long jarg1, Config jarg1_, String jarg2);
  public final static native String Config_getString(long jarg1, Config jarg1_, String jarg2);
  public final static native long new_FrontEnd(long jarg1);
  public final static native void delete_FrontEnd(long jarg1);
  public final static native int FrontEnd_outputSize(long jarg1, FrontEnd jarg1_);
  public final static native void FrontEnd_startUtt(long jarg1, FrontEnd jarg1_);
  public final static native long FrontEnd_processUtt(long jarg1, FrontEnd jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long FrontEnd_endUtt(long jarg1, FrontEnd jarg1_, long jarg2);
  public final static native long new_Feature(long jarg1);
  public final static native void delete_Feature(long jarg1);
  public final static native long new_FsgModel(long jarg1);
  public final static native void delete_FsgModel(long jarg1);
  public final static native int FsgModel_wordId(long jarg1, FsgModel jarg1_, String jarg2);
  public final static native int FsgModel_wordAdd(long jarg1, FsgModel jarg1_, String jarg2);
  public final static native void FsgModel_transAdd(long jarg1, FsgModel jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long FsgModel_nullTransAdd(long jarg1, FsgModel jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native long FsgModel_tagTransAdd(long jarg1, FsgModel jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int FsgModel_addSilence(long jarg1, FsgModel jarg1_, String jarg2, int jarg3, long jarg4);
  public final static native int FsgModel_addAlt(long jarg1, FsgModel jarg1_, String jarg2, String jarg3);
  public final static native void FsgModel_write(long jarg1, FsgModel jarg1_, long jarg2);
  public final static native void FsgModel_writefile(long jarg1, FsgModel jarg1_, String jarg2);
  public final static native long new_Jsgf(String jarg1);
  public final static native void delete_Jsgf(long jarg1);
  public final static native String Jsgf_name(long jarg1, Jsgf jarg1_);
  public final static native long Jsgf_getRule(long jarg1, Jsgf jarg1_, String jarg2);
  public final static native long Jsgf_buildFsg(long jarg1, Jsgf jarg1_, long jarg2, long jarg3, float jarg4);
  public final static native long new_NGramModel(String jarg1);
  public final static native void delete_NGramModel(long jarg1);
  public final static native void NGramModel_write(long jarg1, NGramModel jarg1_, String jarg2, long jarg3);
  public final static native long NGramModel_strToType(long jarg1, NGramModel jarg1_, String jarg2);
  public final static native String NGramModel_typeToStr(long jarg1, NGramModel jarg1_, int jarg2);
  public final static native void NGramModel_recode(long jarg1, NGramModel jarg1_, String jarg2, String jarg3);
  public final static native void NGramModel_casefold(long jarg1, NGramModel jarg1_, int jarg2);
  public final static native long NGramModel_size(long jarg1, NGramModel jarg1_);
  public final static native long NGramModel_addWord(long jarg1, NGramModel jarg1_, String jarg2, long jarg3);
  public final static native long NGramModel_addClass(long jarg1, NGramModel jarg1_, String jarg2, long jarg3, long jarg4, long jarg5, long jarg6);
  public final static native void NGramModelSetIterator_ptr_set(long jarg1, NGramModelSetIterator jarg1_, long jarg2);
  public final static native long NGramModelSetIterator_ptr_get(long jarg1, NGramModelSetIterator jarg1_);
  public final static native long new_NGramModelSetIterator(long jarg1);
  public final static native void delete_NGramModelSetIterator(long jarg1);
  public final static native long NGramModelSetIterator_next(long jarg1, NGramModelSetIterator jarg1_);
  public final static native long NGramModelSet_iter(long jarg1, NGramModelSet jarg1_);
  public final static native long new_NGramModelSet(String jarg1);
  public final static native void delete_NGramModelSet(long jarg1);
  public final static native long NGramModelSet_count(long jarg1, NGramModelSet jarg1_);
  public final static native long NGramModelSet_add(long jarg1, NGramModelSet jarg1_, long jarg2, NGramModel jarg2_, String jarg3, float jarg4, int jarg5);
  public final static native long NGramModelSet_select(long jarg1, NGramModelSet jarg1_, String jarg2);
  public final static native long NGramModelSet_lookup(long jarg1, NGramModelSet jarg1_, String jarg2);
  public final static native String NGramModelSet_current(long jarg1, NGramModelSet jarg1_);
  public final static native int setLogFile(String jarg1);
}
